; =========================================
; 共通設定 (すべての環境で適用されます)
; =========================================
[env]
platform = espressif32
; ボードを M5Stack CoreS3 から M5Stack Basic/Core に変更
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = 
	m5stack/M5Unified
	m5stack/M5Unit-ENV
    crankyoldgit/IRremoteESP8266 @ ^2.8.6

[env:test_env]
build_src_filter = -<*> +<test_env.cpp>

[env:ir_input]
build_src_filter = -<*> +<ir_input.cpp>

[env:test_display]
build_src_filter = -<*> +<test_display.cpp>

[env:ir_send]
build_src_filter = -<*> +<ir_send.cpp>

[env:auto_adjust]
build_src_filter = -<*> +<auto_adjust.cpp>
lib_deps = 
    ${env.lib_deps}
    bblanchon/ArduinoJson @ ^6.21.3 ; 天気APIのJSON解析用